#!/bin/bash

cd ./source/

source ./scripts/aenv
source ./scripts/aaddtopath

printf "Commands imported:\n\n"
printf "acheck_requirements - check project requirements\n"
printf "abuild - build the project\n"
printf "aupload - upload to the target board\n"
printf "acmds_test - run the commands test script\n\n"

cd -
