#!/bin/bash

cd ./source/

source ./scripts/pienv
source ./scripts/piaddtopath

# Create empty file for the logging
touch  ./source/python/logs/smarthome.log

printf "Commands imported:\n\n"
printf "picheck_requirements - check project requirements\n"
printf "pistart_server - start the web server\n\n"

cd -
