#!/bin/bash

cd ./source/

source ./scripts/pienv
source ./scripts/piaddtopath

# Create empty file for the logging
if [ ! -d "./python/logs" ]
then
    mkdir ./python/logs
fi

touch  ./python/logs/smarthome.log

printf "Commands imported:\n\n"
printf "picheck_requirements - check project requirements\n"
printf "pistart_server - start the web server\n\n"

cd -
